echo "-----------------------------------"
echo "Zipbox v0.1"
echo "-------------------------------------"
echo "a java app to zip/unzip files and folders"
echo "-------------------------------------"
echo "Minimum Requirements:"
echo ""
echo "- needs Java 1.7 or above"
echo "-------------------------------------"
echo "Developed By : deepak pk"
echo "Email : deepakpk009@yahoo.in"
echo "-------------------------------------"
echo "This Project is Licensed under LGPL"
echo "-------------------------------------"
echo ""
echo "This program is free software: you can redistribute it and/or modify"
echo "it under the terms of the GNU Lesser General Public License as published by"
echo "the Free Software Foundation, either version 3 of the License, or"
echo "(at your option) any later version."
echo ""
echo "This program is distributed in the hope that it will be useful,"
echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
echo "GNU General Public License for more details."
echo ""
echo "You should have received a copy of the GNU Lesser General Public License"
echo "along with this program.  If not, see <http://www.gnu.org/licenses/>."
echo "Running the application in root/super user mode:"
java -jar dist/Zipbox.jar
